/*
 * generated by Xtext 2.37.0
 */
package org.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDungeonDSLScopeProvider extends DelegatingScopeProvider {
}
