/**
 * generated by Xtext 2.37.0
 */
package org.dungeonDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.dungeonDSL.DungeonDSLPackage
 * @generated
 */
public interface DungeonDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DungeonDSLFactory eINSTANCE = org.dungeonDSL.impl.DungeonDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Dungeon</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dungeon</em>'.
   * @generated
   */
  Dungeon createDungeon();

  /**
   * Returns a new object of class '<em>Floor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Floor</em>'.
   * @generated
   */
  Floor createFloor();

  /**
   * Returns a new object of class '<em>Room</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Room</em>'.
   * @generated
   */
  Room createRoom();

  /**
   * Returns a new object of class '<em>Trap</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trap</em>'.
   * @generated
   */
  Trap createTrap();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DungeonDSLPackage getDungeonDSLPackage();

} //DungeonDSLFactory
