/**
 * generated by Xtext 2.37.0
 */
package org.dungeonDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trap</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.dungeonDSL.Trap#getName <em>Name</em>}</li>
 *   <li>{@link org.dungeonDSL.Trap#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link org.dungeonDSL.Trap#getDisarmable <em>Disarmable</em>}</li>
 *   <li>{@link org.dungeonDSL.Trap#getTriggerChance <em>Trigger Chance</em>}</li>
 * </ul>
 *
 * @see org.dungeonDSL.DungeonDSLPackage#getTrap()
 * @model
 * @generated
 */
public interface Trap extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.dungeonDSL.DungeonDSLPackage#getTrap_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.dungeonDSL.Trap#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Trigger</b></em>' attribute.
   * The literals are from the enumeration {@link org.dungeonDSL.EventTrigger}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger</em>' attribute.
   * @see org.dungeonDSL.EventTrigger
   * @see #setTrigger(EventTrigger)
   * @see org.dungeonDSL.DungeonDSLPackage#getTrap_Trigger()
   * @model
   * @generated
   */
  EventTrigger getTrigger();

  /**
   * Sets the value of the '{@link org.dungeonDSL.Trap#getTrigger <em>Trigger</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger</em>' attribute.
   * @see org.dungeonDSL.EventTrigger
   * @see #getTrigger()
   * @generated
   */
  void setTrigger(EventTrigger value);

  /**
   * Returns the value of the '<em><b>Disarmable</b></em>' attribute.
   * The literals are from the enumeration {@link org.dungeonDSL.BOOLEAN}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Disarmable</em>' attribute.
   * @see org.dungeonDSL.BOOLEAN
   * @see #setDisarmable(BOOLEAN)
   * @see org.dungeonDSL.DungeonDSLPackage#getTrap_Disarmable()
   * @model
   * @generated
   */
  BOOLEAN getDisarmable();

  /**
   * Sets the value of the '{@link org.dungeonDSL.Trap#getDisarmable <em>Disarmable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Disarmable</em>' attribute.
   * @see org.dungeonDSL.BOOLEAN
   * @see #getDisarmable()
   * @generated
   */
  void setDisarmable(BOOLEAN value);

  /**
   * Returns the value of the '<em><b>Trigger Chance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger Chance</em>' attribute.
   * @see #setTriggerChance(int)
   * @see org.dungeonDSL.DungeonDSLPackage#getTrap_TriggerChance()
   * @model
   * @generated
   */
  int getTriggerChance();

  /**
   * Sets the value of the '{@link org.dungeonDSL.Trap#getTriggerChance <em>Trigger Chance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger Chance</em>' attribute.
   * @see #getTriggerChance()
   * @generated
   */
  void setTriggerChance(int value);

} // Trap
