/**
 * generated by Xtext 2.37.0
 */
package org.tests;

import com.google.inject.Inject;
import org.eclipse.xtend.lib.Property;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(DungeonDSLInjectorProvider.class)
@SuppressWarnings("all")
public class DungeonDSLParsingTest {
  @Inject
  private ParseHelper<Property> parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field eResource is undefined for the type Property"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
