/**
 * generated by Xtext 2.37.0
 */
package org.dungeonDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dungeon</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.dungeonDSL.Dungeon#getName <em>Name</em>}</li>
 *   <li>{@link org.dungeonDSL.Dungeon#getTheme <em>Theme</em>}</li>
 *   <li>{@link org.dungeonDSL.Dungeon#getLvl <em>Lvl</em>}</li>
 *   <li>{@link org.dungeonDSL.Dungeon#getFloors <em>Floors</em>}</li>
 * </ul>
 *
 * @see org.dungeonDSL.DungeonDSLPackage#getDungeon()
 * @model
 * @generated
 */
public interface Dungeon extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.dungeonDSL.DungeonDSLPackage#getDungeon_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.dungeonDSL.Dungeon#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Theme</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Theme</em>' attribute.
   * @see #setTheme(String)
   * @see org.dungeonDSL.DungeonDSLPackage#getDungeon_Theme()
   * @model
   * @generated
   */
  String getTheme();

  /**
   * Sets the value of the '{@link org.dungeonDSL.Dungeon#getTheme <em>Theme</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Theme</em>' attribute.
   * @see #getTheme()
   * @generated
   */
  void setTheme(String value);

  /**
   * Returns the value of the '<em><b>Lvl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lvl</em>' attribute.
   * @see #setLvl(int)
   * @see org.dungeonDSL.DungeonDSLPackage#getDungeon_Lvl()
   * @model
   * @generated
   */
  int getLvl();

  /**
   * Sets the value of the '{@link org.dungeonDSL.Dungeon#getLvl <em>Lvl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lvl</em>' attribute.
   * @see #getLvl()
   * @generated
   */
  void setLvl(int value);

  /**
   * Returns the value of the '<em><b>Floors</b></em>' containment reference list.
   * The list contents are of type {@link org.dungeonDSL.Floor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Floors</em>' containment reference list.
   * @see org.dungeonDSL.DungeonDSLPackage#getDungeon_Floors()
   * @model containment="true"
   * @generated
   */
  EList<Floor> getFloors();

} // Dungeon
