/**
 * generated by Xtext 2.37.0
 */
package org.dungeonDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.dungeonDSL.DungeonDSLFactory
 * @model kind="package"
 * @generated
 */
public interface DungeonDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dungeonDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.DungeonDSL.org";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dungeonDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DungeonDSLPackage eINSTANCE = org.dungeonDSL.impl.DungeonDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.dungeonDSL.impl.DungeonImpl <em>Dungeon</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.dungeonDSL.impl.DungeonImpl
   * @see org.dungeonDSL.impl.DungeonDSLPackageImpl#getDungeon()
   * @generated
   */
  int DUNGEON = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DUNGEON__NAME = 0;

  /**
   * The feature id for the '<em><b>Theme</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DUNGEON__THEME = 1;

  /**
   * The feature id for the '<em><b>Lvl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DUNGEON__LVL = 2;

  /**
   * The feature id for the '<em><b>Floors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DUNGEON__FLOORS = 3;

  /**
   * The number of structural features of the '<em>Dungeon</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DUNGEON_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.dungeonDSL.impl.FloorImpl <em>Floor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.dungeonDSL.impl.FloorImpl
   * @see org.dungeonDSL.impl.DungeonDSLPackageImpl#getFloor()
   * @generated
   */
  int FLOOR = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Rooms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOOR__ROOMS = 1;

  /**
   * The number of structural features of the '<em>Floor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.dungeonDSL.impl.RoomImpl <em>Room</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.dungeonDSL.impl.RoomImpl
   * @see org.dungeonDSL.impl.DungeonDSLPackageImpl#getRoom()
   * @generated
   */
  int ROOM = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__NAME = 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__SIZE = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__TYPE = 2;

  /**
   * The number of structural features of the '<em>Room</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.dungeonDSL.Sizes <em>Sizes</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.dungeonDSL.Sizes
   * @see org.dungeonDSL.impl.DungeonDSLPackageImpl#getSizes()
   * @generated
   */
  int SIZES = 3;

  /**
   * The meta object id for the '{@link org.dungeonDSL.RoomTypes <em>Room Types</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.dungeonDSL.RoomTypes
   * @see org.dungeonDSL.impl.DungeonDSLPackageImpl#getRoomTypes()
   * @generated
   */
  int ROOM_TYPES = 4;


  /**
   * Returns the meta object for class '{@link org.dungeonDSL.Dungeon <em>Dungeon</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dungeon</em>'.
   * @see org.dungeonDSL.Dungeon
   * @generated
   */
  EClass getDungeon();

  /**
   * Returns the meta object for the attribute '{@link org.dungeonDSL.Dungeon#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.dungeonDSL.Dungeon#getName()
   * @see #getDungeon()
   * @generated
   */
  EAttribute getDungeon_Name();

  /**
   * Returns the meta object for the attribute '{@link org.dungeonDSL.Dungeon#getTheme <em>Theme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Theme</em>'.
   * @see org.dungeonDSL.Dungeon#getTheme()
   * @see #getDungeon()
   * @generated
   */
  EAttribute getDungeon_Theme();

  /**
   * Returns the meta object for the attribute '{@link org.dungeonDSL.Dungeon#getLvl <em>Lvl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lvl</em>'.
   * @see org.dungeonDSL.Dungeon#getLvl()
   * @see #getDungeon()
   * @generated
   */
  EAttribute getDungeon_Lvl();

  /**
   * Returns the meta object for the containment reference list '{@link org.dungeonDSL.Dungeon#getFloors <em>Floors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Floors</em>'.
   * @see org.dungeonDSL.Dungeon#getFloors()
   * @see #getDungeon()
   * @generated
   */
  EReference getDungeon_Floors();

  /**
   * Returns the meta object for class '{@link org.dungeonDSL.Floor <em>Floor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Floor</em>'.
   * @see org.dungeonDSL.Floor
   * @generated
   */
  EClass getFloor();

  /**
   * Returns the meta object for the attribute '{@link org.dungeonDSL.Floor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.dungeonDSL.Floor#getName()
   * @see #getFloor()
   * @generated
   */
  EAttribute getFloor_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.dungeonDSL.Floor#getRooms <em>Rooms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rooms</em>'.
   * @see org.dungeonDSL.Floor#getRooms()
   * @see #getFloor()
   * @generated
   */
  EReference getFloor_Rooms();

  /**
   * Returns the meta object for class '{@link org.dungeonDSL.Room <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room</em>'.
   * @see org.dungeonDSL.Room
   * @generated
   */
  EClass getRoom();

  /**
   * Returns the meta object for the attribute '{@link org.dungeonDSL.Room#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.dungeonDSL.Room#getName()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Name();

  /**
   * Returns the meta object for the attribute '{@link org.dungeonDSL.Room#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see org.dungeonDSL.Room#getSize()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Size();

  /**
   * Returns the meta object for the attribute '{@link org.dungeonDSL.Room#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.dungeonDSL.Room#getType()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Type();

  /**
   * Returns the meta object for enum '{@link org.dungeonDSL.Sizes <em>Sizes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Sizes</em>'.
   * @see org.dungeonDSL.Sizes
   * @generated
   */
  EEnum getSizes();

  /**
   * Returns the meta object for enum '{@link org.dungeonDSL.RoomTypes <em>Room Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Room Types</em>'.
   * @see org.dungeonDSL.RoomTypes
   * @generated
   */
  EEnum getRoomTypes();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DungeonDSLFactory getDungeonDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.dungeonDSL.impl.DungeonImpl <em>Dungeon</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.dungeonDSL.impl.DungeonImpl
     * @see org.dungeonDSL.impl.DungeonDSLPackageImpl#getDungeon()
     * @generated
     */
    EClass DUNGEON = eINSTANCE.getDungeon();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DUNGEON__NAME = eINSTANCE.getDungeon_Name();

    /**
     * The meta object literal for the '<em><b>Theme</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DUNGEON__THEME = eINSTANCE.getDungeon_Theme();

    /**
     * The meta object literal for the '<em><b>Lvl</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DUNGEON__LVL = eINSTANCE.getDungeon_Lvl();

    /**
     * The meta object literal for the '<em><b>Floors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DUNGEON__FLOORS = eINSTANCE.getDungeon_Floors();

    /**
     * The meta object literal for the '{@link org.dungeonDSL.impl.FloorImpl <em>Floor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.dungeonDSL.impl.FloorImpl
     * @see org.dungeonDSL.impl.DungeonDSLPackageImpl#getFloor()
     * @generated
     */
    EClass FLOOR = eINSTANCE.getFloor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLOOR__NAME = eINSTANCE.getFloor_Name();

    /**
     * The meta object literal for the '<em><b>Rooms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOOR__ROOMS = eINSTANCE.getFloor_Rooms();

    /**
     * The meta object literal for the '{@link org.dungeonDSL.impl.RoomImpl <em>Room</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.dungeonDSL.impl.RoomImpl
     * @see org.dungeonDSL.impl.DungeonDSLPackageImpl#getRoom()
     * @generated
     */
    EClass ROOM = eINSTANCE.getRoom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__NAME = eINSTANCE.getRoom_Name();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__SIZE = eINSTANCE.getRoom_Size();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__TYPE = eINSTANCE.getRoom_Type();

    /**
     * The meta object literal for the '{@link org.dungeonDSL.Sizes <em>Sizes</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.dungeonDSL.Sizes
     * @see org.dungeonDSL.impl.DungeonDSLPackageImpl#getSizes()
     * @generated
     */
    EEnum SIZES = eINSTANCE.getSizes();

    /**
     * The meta object literal for the '{@link org.dungeonDSL.RoomTypes <em>Room Types</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.dungeonDSL.RoomTypes
     * @see org.dungeonDSL.impl.DungeonDSLPackageImpl#getRoomTypes()
     * @generated
     */
    EEnum ROOM_TYPES = eINSTANCE.getRoomTypes();

  }

} //DungeonDSLPackage
