/**
 * generated by Xtext 2.37.0
 */
package org.dungeonDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Floor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.dungeonDSL.Floor#getName <em>Name</em>}</li>
 *   <li>{@link org.dungeonDSL.Floor#getRooms <em>Rooms</em>}</li>
 * </ul>
 *
 * @see org.dungeonDSL.DungeonDSLPackage#getFloor()
 * @model
 * @generated
 */
public interface Floor extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.dungeonDSL.DungeonDSLPackage#getFloor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.dungeonDSL.Floor#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Rooms</b></em>' containment reference list.
   * The list contents are of type {@link org.dungeonDSL.Room}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rooms</em>' containment reference list.
   * @see org.dungeonDSL.DungeonDSLPackage#getFloor_Rooms()
   * @model containment="true"
   * @generated
   */
  EList<Room> getRooms();

} // Floor
