/**
 * generated by Xtext 2.37.0
 */
package org.dungeonDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Room</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.dungeonDSL.Room#getName <em>Name</em>}</li>
 *   <li>{@link org.dungeonDSL.Room#getSize <em>Size</em>}</li>
 *   <li>{@link org.dungeonDSL.Room#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.dungeonDSL.DungeonDSLPackage#getRoom()
 * @model
 * @generated
 */
public interface Room extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.dungeonDSL.DungeonDSLPackage#getRoom_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.dungeonDSL.Room#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * The literals are from the enumeration {@link org.dungeonDSL.Sizes}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see org.dungeonDSL.Sizes
   * @see #setSize(Sizes)
   * @see org.dungeonDSL.DungeonDSLPackage#getRoom_Size()
   * @model
   * @generated
   */
  Sizes getSize();

  /**
   * Sets the value of the '{@link org.dungeonDSL.Room#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see org.dungeonDSL.Sizes
   * @see #getSize()
   * @generated
   */
  void setSize(Sizes value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.dungeonDSL.RoomTypes}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.dungeonDSL.RoomTypes
   * @see #setType(RoomTypes)
   * @see org.dungeonDSL.DungeonDSLPackage#getRoom_Type()
   * @model
   * @generated
   */
  RoomTypes getType();

  /**
   * Sets the value of the '{@link org.dungeonDSL.Room#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.dungeonDSL.RoomTypes
   * @see #getType()
   * @generated
   */
  void setType(RoomTypes value);

} // Room
