/*
 * generated by Xtext 2.37.0
 */
package org.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.dungeondsl.ui.internal.DungeondslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DungeonDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DungeondslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DungeondslActivator activator = DungeondslActivator.getInstance();
		return activator != null ? activator.getInjector(DungeondslActivator.ORG_DUNGEONDSL) : null;
	}

}
