/*
 * generated by Xtext 2.37.0
 */
package org.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.DungeonDSLRuntimeModule;
import org.DungeonDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DungeonDSLIdeSetup extends DungeonDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DungeonDSLRuntimeModule(), new DungeonDSLIdeModule()));
	}
	
}
