/*
 * generated by Xtext 2.37.0
 */
package org.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.dungeondsl.ui.internal.DungeondslActivator;

public class DungeonDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DungeondslActivator.getInstance().getInjector("org.DungeonDSL");
	}

}
